### ISSUE TITLE
Typo in the mnemonic section

### ISSUE THREAD

**Issue by RobinWragg** [lmmendes/game-boy-opcodes#2]
I'm fairly new to assembly, but I think this line:
"LD C,(A) has alternative mnemonic LD ($FF00+C),A"
Should have the parenthesis around the C, not the A.
This is my proposed corrected line:
"LD (C),A has alternative mnemonic LD ($FF00+C),A"

**Comment by lmmendes** [comment]
Hi @RobinWragg, I tend to agree with your observation but let me check the documentation, and will update the ticket after that.

**Comment by lmmendes** [comment]
@RobinWragg after a little bit more digging on the gameboy manual  I remembered that there are two distinct LD types of operations, the `LD C,A`  with the  opcode `0x4F` and `LD (C),A` with the opcode `0xE2`:

The file [opcodes.json](https://github.com/lmmendes/game-boy-opcodes/blob/master/opcodes.json) define both in the following form:

```
"0x4f": {
      "mnemonic": "LD",
      "length": 1,
      "cycles": [
        4
      ],
      "flags": [
        "-",
        "-",
        "-",
        "-"
      ],
      "addr": "0x4f",
      "operand1": "C",
      "operand2": "A"
    },
```

```
"0xe2": {
      "mnemonic": "LD",
      "length": 2,
      "cycles": [
        8
      ],
      "flags": [
        "-",
        "-",
        "-",
        "-"
      ],
      "addr": "0xe2",
      "operand1": "(C)",
      "operand2": "A"
    },
```

You can check the values against the [Gameboy CPU Manual](http://marc.rawer.de/Gameboy/Docs/GBCPUman.pdf) on page 69 and 70; or see the following images:

Page 69:

<img width="462" alt="page-69" src="https://user-images.githubusercontent.com/114094/48511422-93d36d00-e84e-11e8-8caa-34291342c21f.png">

Page 70:

<img width="409" alt="page-70" src="https://user-images.githubusercontent.com/114094/48511320-47882d00-e84e-11e8-9501-941f5e133514.png">

**Comment by lmmendes** [comment]
I'm closing this since it's a non issue.
